"""create transform_jobs table

Revision ID: 8e45dd8ca598
Revises: 
Create Date: 2024-07-04 09:55:46.693715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e45dd8ca598'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_jobs_extraction_job_id'), 'transformation_jobs', ['extraction_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transformation_jobs_extraction_job_id'), table_name='transformation_jobs')
    op.drop_table('transformation_jobs')
    # ### end Alembic commands ###
